from datetime import date

from jinja2 import Template

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FinOps Daily - {{ dt }}</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #07070d; color: #e2e8f0; line-height: 1.7; padding: 2rem; -webkit-font-smoothing: antialiased; }
.container { max-width: 900px; margin: 0 auto; }
h1 { font-size: 2rem; font-weight: 800; letter-spacing: -0.03em; background: linear-gradient(135deg, #f1f5f9 0%, #60a5fa 50%, #a78bfa 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin-bottom: .25rem; }
.subtitle { color: #64748b; margin-bottom: 2rem; }
.stats { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
.stat { background: #0d0d18; border: 1px solid rgba(255,255,255,0.05); border-radius: 12px; padding: 1rem 1.5rem; text-align: center; flex:1; min-width:100px; }
.stat-value { font-size: 1.5rem; font-weight: 800; color: #60a5fa; }
.stat-label { font-size: .75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
.section { margin-bottom: 2rem; }
h2 { color: #fbbf24; font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem; padding-bottom: .5rem; border-bottom: 1px solid rgba(255,255,255,0.05); }
.card { background: #0d0d18; border: 1px solid rgba(255,255,255,0.05); border-radius: 12px; padding: 1.25rem; margin-bottom: .75rem; transition: all 0.25s; }
.card:hover { border-color: rgba(96,165,250,0.2); }
.card h3 { font-size: 0.95rem; font-weight: 600; margin-bottom: .25rem; }
.card h3 a { color: #e2e8f0; text-decoration: none; }
.card h3 a:hover { color: #60a5fa; }
.card .meta { font-size: .8rem; color: #64748b; }
.card .meta span { margin-right: 1rem; }
.card .summary { font-size: .85rem; color: #94a3b8; margin-top: .5rem; line-height: 1.6; }
.tag { display: inline-block; background: linear-gradient(135deg, rgba(96,165,250,0.1), rgba(167,139,250,0.1)); color: #a78bfa; font-size: .7rem; font-weight: 500; padding: .15rem .6rem; border-radius: 999px; margin-right: .25rem; border: 1px solid rgba(167,139,250,0.15); }
.search-box { margin-bottom: 1.5rem; }
.search-box input { width: 100%; padding: .875rem 1.25rem; background: #0d0d18; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; color: #f1f5f9; font-size: 1rem; font-family: 'Inter', sans-serif; outline: none; }
.search-box input::placeholder { color: #475569; }
.search-box input:focus { border-color: rgba(96,165,250,0.4); box-shadow: 0 0 0 3px rgba(96,165,250,0.08); }
.footer { text-align: center; color: #334155; font-size: .8rem; margin-top: 3rem; }
.footer a { color: #475569; }
.footer a:hover { color: #60a5fa; }
</style>
</head>
<body>
<div class="container">
<h1>☁️ FinOps Daily Intelligence</h1>
<p class="subtitle">{{ dt }} · Generated by FinOps Agent</p>

<div class="stats">
<div class="stat"><div class="stat-value">{{ items|length }}</div><div class="stat-label">Items</div></div>
<div class="stat"><div class="stat-value">{{ sources|length }}</div><div class="stat-label">Sources</div></div>
<div class="stat"><div class="stat-value">{{ categories|length }}</div><div class="stat-label">Categories</div></div>
</div>

<div class="search-box">
<input type="text" id="search" placeholder="Search items..." onkeyup="filterItems()">
</div>

{% for cat, cat_items in grouped.items() %}
<div class="section" data-category="{{ cat }}">
<h2>{% if cat == 'tools' %}🛠️{% elif cat == 'aws' %}☁️{% elif cat == 'gcp' %}☁️{% elif cat == 'azure' %}☁️{% elif cat == 'community' %}📰{% else %}📌{% endif %} {{ cat|capitalize }}</h2>
{% for item in cat_items %}
<div class="card searchable" data-title="{{ item.title|lower }}" data-summary="{{ (item.summary or '')|lower }}">
<h3><a href="{{ item.url }}" target="_blank" rel="noopener">{{ item.title }}</a></h3>
<div class="meta">
<span>📅 {{ item.date }}</span>
<span>🔗 {{ item.source_name or item.source_id }}</span>
{% if item.tags %}<span>🏷️ {% for tag in item.tags.split(',') %}<span class="tag">{{ tag.strip() }}</span> {% endfor %}</span>{% endif %}
</div>
{% if item.summary %}<div class="summary">{{ item.summary[:300] }}{% if item.summary|length > 300 %}…{% endif %}</div>{% endif %}
</div>
{% endfor %}
</div>
{% endfor %}

<div class="footer">
FinOps Intelligence Agent · <a href="https://github.com/your-org/finops-agent" style="color: #38bdf8;">GitHub</a>
</div>
</div>

<script>
function filterItems() {
const q = document.getElementById('search').value.toLowerCase();
document.querySelectorAll('.searchable').forEach(el => {
const match = el.dataset.title.includes(q) || el.dataset.summary.includes(q);
el.style.display = match ? '' : 'none';
});
}
</script>
</body>
</html>"""


class HTMLReporter:
    def __init__(self, config: dict, db):
        self.config = config
        self.db = db

    def generate(self, dt: str, output_path: str):
        items = self.db.get_items_by_date(dt)
        if not items:
            items = self.db.get_items(limit=100)

        sources = set(i.get("source_name", i.get("source_id")) for i in items)
        categories = set(i.get("category", "general") for i in items)

        grouped = {}
        for item in items:
            cat = item.get("category", "general")
            grouped.setdefault(cat, []).append(item)

        template = Template(REPORT_TEMPLATE)
        html = template.render(
            dt=dt,
            items=items,
            sources=sources,
            categories=categories,
            grouped=grouped,
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
