from datetime import date

from jinja2 import Template

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FinOps Daily - {{ dt }}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; padding: 2rem; }
.container { max-width: 900px; margin: 0 auto; }
h1 { color: #38bdf8; font-size: 1.8rem; margin-bottom: .25rem; }
.subtitle { color: #94a3b8; margin-bottom: 2rem; }
.stats { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
.stat { background: #1e293b; padding: 1rem 1.5rem; border-radius: .5rem; text-align: center; }
.stat-value { font-size: 1.5rem; font-weight: 700; color: #38bdf8; }
.stat-label { font-size: .75rem; color: #94a3b8; text-transform: uppercase; }
.section { margin-bottom: 2rem; }
h2 { color: #facc15; font-size: 1.2rem; margin-bottom: 1rem; padding-bottom: .5rem; border-bottom: 1px solid #334155; }
.card { background: #1e293b; border-radius: .5rem; padding: 1rem; margin-bottom: .75rem; }
.card h3 { font-size: 1rem; margin-bottom: .25rem; }
.card h3 a { color: #e2e8f0; text-decoration: none; }
.card h3 a:hover { color: #38bdf8; }
.card .meta { font-size: .8rem; color: #94a3b8; }
.card .meta span { margin-right: 1rem; }
.card .summary { font-size: .875rem; color: #cbd5e1; margin-top: .5rem; }
.tag { display: inline-block; background: #334155; color: #38bdf8; font-size: .7rem; padding: .15rem .5rem; border-radius: 999px; margin-right: .25rem; }
.search-box { margin-bottom: 1.5rem; }
.search-box input { width: 100%; padding: .75rem 1rem; background: #1e293b; border: 1px solid #334155; border-radius: .5rem; color: #e2e8f0; font-size: 1rem; }
.search-box input:focus { outline: none; border-color: #38bdf8; }
.footer { text-align: center; color: #475569; font-size: .8rem; margin-top: 3rem; }
</style>
</head>
<body>
<div class="container">
<h1>☁️ FinOps Daily Intelligence</h1>
<p class="subtitle">{{ dt }} · Generated by FinOps Agent</p>

<div class="stats">
<div class="stat"><div class="stat-value">{{ items|length }}</div><div class="stat-label">Items</div></div>
<div class="stat"><div class="stat-value">{{ sources|length }}</div><div class="stat-label">Sources</div></div>
<div class="stat"><div class="stat-value">{{ categories|length }}</div><div class="stat-label">Categories</div></div>
</div>

<div class="search-box">
<input type="text" id="search" placeholder="Search items..." onkeyup="filterItems()">
</div>

{% for cat, cat_items in grouped.items() %}
<div class="section" data-category="{{ cat }}">
<h2>{% if cat == 'tools' %}🛠️{% elif cat == 'aws' %}☁️{% elif cat == 'gcp' %}☁️{% elif cat == 'azure' %}☁️{% elif cat == 'community' %}📰{% else %}📌{% endif %} {{ cat|capitalize }}</h2>
{% for item in cat_items %}
<div class="card searchable" data-title="{{ item.title|lower }}" data-summary="{{ (item.summary or '')|lower }}">
<h3><a href="{{ item.url }}" target="_blank" rel="noopener">{{ item.title }}</a></h3>
<div class="meta">
<span>📅 {{ item.date }}</span>
<span>🔗 {{ item.source_name or item.source_id }}</span>
{% if item.tags %}<span>🏷️ {% for tag in item.tags.split(',') %}<span class="tag">{{ tag.strip() }}</span> {% endfor %}</span>{% endif %}
</div>
{% if item.summary %}<div class="summary">{{ item.summary[:300] }}{% if item.summary|length > 300 %}…{% endif %}</div>{% endif %}
</div>
{% endfor %}
</div>
{% endfor %}

<div class="footer">
FinOps Intelligence Agent · <a href="https://github.com/your-org/finops-agent" style="color: #38bdf8;">GitHub</a>
</div>
</div>

<script>
function filterItems() {
const q = document.getElementById('search').value.toLowerCase();
document.querySelectorAll('.searchable').forEach(el => {
const match = el.dataset.title.includes(q) || el.dataset.summary.includes(q);
el.style.display = match ? '' : 'none';
});
}
</script>
</body>
</html>"""


class HTMLReporter:
    def __init__(self, config: dict, db):
        self.config = config
        self.db = db

    def generate(self, dt: str, output_path: str):
        items = self.db.get_items_by_date(dt)
        if not items:
            items = self.db.get_items(limit=100)

        sources = set(i.get("source_name", i.get("source_id")) for i in items)
        categories = set(i.get("category", "general") for i in items)

        grouped = {}
        for item in items:
            cat = item.get("category", "general")
            grouped.setdefault(cat, []).append(item)

        template = Template(REPORT_TEMPLATE)
        html = template.render(
            dt=dt,
            items=items,
            sources=sources,
            categories=categories,
            grouped=grouped,
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
